<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>QuickBuy</title>

		<link rel="stylesheet" href="https://bootswatch.com/4/litera/bootstrap.min.css" />
		<link rel="stylesheet" href="css/styles.css" />
        <script type="module" src="checkout.js" defer></script>
		<script src="https://kit.fontawesome.com/8aa396f8e9.js" crossorigin="anonymous"></script>
	</head>
	<body>
		<?php require_once "./views/layout/navbar.phtml" ?>

		<div class="container">
			<div class="row my-5">
				<div class="col-md-12">
                    <div class="checkout-page" id="page-container">
                        <div class="cart-page">
                            <div class="cart-header">
                                <h1>Shopping Cart</h1>
                                <p><span class='items' id="cart-num">0</span> items in your cart</p>
                            </div>
                            <div class="cart-product-head">
                                <h5 class='heading'>Product</h5>
                                <h5 class='heading'>Price</h5>
                                <h5 class='heading'>Quantity</h5>
                            </div>
                            <div class="cart-product-body" id="product-body">

                            </div>
                        </div>
                        <hr />
                        <div class="contain">
                            <h3>
                                Total: £<span id="total-price">2</span>
                            </h3>
                            <button class="btn btn-danger" id="clear">Clear Cart</button>
                        </div>
                        <div class="checkout-btns">
                            <button class="btn btn-success" id="pay-card">Pay by Credit/Debit Card</button>
                            <button class="btn btn-primary" id="pay-paypal">Buy by PayPal</button>
                            <button class="btn btn-dark" id="pay-apple">Pay by Apple Pay </button>
                        </div>
                    </div>
				</div>
			</div>
		</div>

		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
	</body>
</html>
