<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>QuickBuy</title>

		<link rel="stylesheet" href="https://bootswatch.com/4/litera/bootstrap.min.css" />
		<link rel="stylesheet" href="/demo/css/styles.css" />
		<script type="module" src="/demo/demo.js" defer></script>
		<script src="https://kit.fontawesome.com/8aa396f8e9.js" crossorigin="anonymous"></script>
	</head>
	<body>
		<?php require_once "./views/layout/navbar.phtml" ?>

		<div class="container">
			<div class="row my-5">
				<div class="col-md-12">
					<div id="products">
                        <?php foreach ($products as $index => $product) : ?>
                            <div class="card border-secondary mb-3">
                                <div class="card-header"><?= $product->category ?></div>
                                <img src="<?= $product->image ?>" alt="Product Image" class="card-img-top mt-2 w-25 mx-auto" />
                                <div class="card-body">
                                    <h5 class="card-title"><?= $product->title ?></h5>
                                    <p class="card-text"><?= substr($product->description, 0, 100) . "..." ?></p>
                                    <p>£<?= $product->price ?></p>
                                    <button class="btn btn-primary cart-button" id="add-product-<?= $product->id ?>">Add to cart</button>
                                </div>
                            </div>
                        <?php endforeach; ?>
					</div>
				</div>
			</div>
		</div>


		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
	</body>
</html>
